#!/bin/sh
# Rehearses the next upstream merge without touching any branch.
#
#   scripts/workflowleaf/merge-rehearsal.sh [--quick] [--keep] [--into <ref>]
#
# Fetches upstream, merges upstream/main into a throwaway worktree of the fork
# (origin/main unless --into says otherwise), reinstalls from the lockfile the
# merge produced, and runs the WorkflowLeaf checks and T3's own typecheck and
# tests, the same commands T3's CI runs. --quick skips T3's half.
#
# Every rehearsal appends one JSON line to
# $WORKFLOWLEAF_HOME/merge-rehearsals.jsonl (default ~/.workflowleaf): the
# upstream and fork SHAs, what the merge brought in, the files that conflicted,
# the upstream-owned files the fork edits that upstream also changed, whether
# the lockfile had to be regenerated, each step's result and time, and the
# total time. A rehearsal that conflicted or
# failed a step needed surgery. Two in a row that did means the seam needs
# review, and the script says so.
#
# Exits 0 when the merge is clean and every step passed.
set -u

quick=0
keep=0
into=origin/main
while [ $# -gt 0 ]; do
  case $1 in
    --quick) quick=1 ;;
    --keep) keep=1 ;;
    --into) into=$2; shift ;;
    *) echo "usage: $0 [--quick] [--keep] [--into <ref>]" >&2; exit 2 ;;
  esac
  shift
done

repo=$(git rev-parse --show-toplevel) || exit 2
home=${WORKFLOWLEAF_HOME:-$HOME/.workflowleaf}
record=$home/merge-rehearsals.jsonl
node24="$HOME/.nvm/versions/node/v24.20.0/bin"
[ -d "$node24" ] && PATH="$node24:$PATH"

now() { date +%s; }
started=$(now)

git -C "$repo" fetch --quiet upstream main || { echo "Could not fetch upstream." >&2; exit 2; }
git -C "$repo" fetch --quiet origin || { echo "Could not fetch origin." >&2; exit 2; }
upstream_sha=$(git -C "$repo" rev-parse upstream/main)
base_sha=$(git -C "$repo" rev-parse "$into") || exit 2
merge_base=$(git -C "$repo" merge-base "$base_sha" "$upstream_sha")

work=$(mktemp -d "${TMPDIR:-/tmp}/wl-merge-rehearsal.XXXXXX")
git -C "$repo" worktree add --quiet --detach "$work/tree" "$base_sha" || exit 2
tree=$work/tree
cleanup() {
  if [ "$keep" -eq 1 ]; then
    echo "Kept the rehearsal worktree at $tree"
  else
    git -C "$repo" worktree remove --force "$tree" 2>/dev/null
    echo "Step logs are in $work"
  fi
}
trap cleanup EXIT

json_list() { # newline-separated lines on stdin -> JSON array of strings
  awk 'BEGIN { printf "[" } NF { gsub(/\\/, "\\\\"); gsub(/"/, "\\\""); printf "%s\"%s\"", sep, $0; sep = "," } END { printf "]" }'
}

# What upstream changed since the last merge, and which of those files the fork
# also edits under ownership.json. Those are where a merge needs bridge surgery.
incoming=$(git -C "$repo" diff --shortstat "$merge_base" "$upstream_sha")
files_in=$(printf '%s' "$incoming" | awk '{ print $1 + 0 }')
insertions=$(printf '%s' "$incoming" | sed -n 's/.* \([0-9]*\) insertion.*/\1/p')
deletions=$(printf '%s' "$incoming" | sed -n 's/.* \([0-9]*\) deletion.*/\1/p')
commits_in=$(git -C "$repo" rev-list --count "$base_sha..$upstream_sha")
bridged=$(node -e '
  const own = JSON.parse(require("node:fs").readFileSync(process.argv[1], "utf8"));
  console.log(own.allowedUpstreamEdits.map((entry) => entry.path).join("\n"));
' "$tree/scripts/workflowleaf/ownership.json")
bridge_touched=$(git -C "$repo" diff --name-only "$merge_base" "$upstream_sha" | grep -Fx "$bridged" || true)

steps=""
failed=0
step() { # <name> <command...>
  name=$1
  shift
  echo "== $name"
  step_started=$(now)
  if (cd "$tree" && PATH="$tree/node_modules/.bin:$PATH" && "$@") >"$work/$name.log" 2>&1; then ok=true; else ok=false; failed=1; fi
  seconds=$(($(now) - step_started))
  echo "   $ok in ${seconds}s (log: $work/$name.log)"
  [ "$ok" = true ] || tail -20 "$work/$name.log" | sed 's/^/   | /'
  steps="$steps${steps:+,}{\"name\":\"$name\",\"ok\":$ok,\"seconds\":$seconds}"
}

echo "Merging upstream/main $upstream_sha ($commits_in commits, $files_in files) into $into $base_sha"
conflicts=""
lockfile_regenerated=false
if ! git -C "$tree" -c user.name="WorkflowLeaf rehearsal" -c user.email="rehearsal@invalid" \
  merge --no-ff --no-edit --quiet "$upstream_sha" >"$work/merge.log" 2>&1; then
  conflicts=$(git -C "$tree" diff --name-only --diff-filter=U)
  failed=1
  echo "The merge conflicts in:"
  printf '%s\n' "$conflicts" | sed 's/^/   /'
  git -C "$tree" merge --abort 2>/dev/null
else
  # Git merges pnpm-lock.yaml as text, and a textually clean merge of it can
  # still be a lockfile pnpm rejects. The fork's lockfile is regenerated by
  # pnpm (ownership.json), so a rejected one is regenerated here as it would be
  # in the real merge, recorded, and not counted as surgery.
  lockfile_regenerated=false
  step install pnpm install --frozen-lockfile
  if [ "$ok" = false ]; then
    failed=0
    lockfile_regenerated=true
    step install-regenerated pnpm install --no-frozen-lockfile
  fi
  # The fork's own changes are what the merge leaves on top of upstream, so the
  # ownership gate is judged against upstream's tip, not the recorded base.
  step workflowleaf-check node scripts/workflowleaf/check.ts --base "$upstream_sha"
  step workflowleaf-typecheck sh -c 'vp run --filter @t3tools/workflowleaf-core typecheck && vp run --filter @t3tools/workflowleaf-runtime typecheck'
  step workflowleaf-test vp test run packages/workflowleaf-core packages/workflowleaf-runtime scripts/workflowleaf
  if [ "$quick" -eq 0 ]; then
    step t3-typecheck vp run -r --concurrency-limit 2 typecheck
    step t3-test vp run --parallel --concurrency-limit 4 --filter '!t3' --filter '!@t3tools/monorepo' test
    step t3-server-test vp run --filter t3 test
  fi
fi

total=$(($(now) - started))
surgery=false
[ "$failed" -eq 1 ] && surgery=true

mkdir -p "$home"
previous=$(tail -n 1 "$record" 2>/dev/null || true)
printf '{"at":"%s","upstreamSha":"%s","into":"%s","baseSha":"%s","upstreamCommits":%s,"filesIn":%s,"insertions":%s,"deletions":%s,"conflicts":%s,"bridgeFilesTouched":%s,"lockfileRegenerated":%s,"quick":%s,"steps":[%s],"seconds":%s,"neededSurgery":%s}\n' \
  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$upstream_sha" "$into" "$base_sha" "$commits_in" \
  "${files_in:-0}" "${insertions:-0}" "${deletions:-0}" \
  "$(printf '%s\n' "$conflicts" | json_list)" "$(printf '%s\n' "$bridge_touched" | json_list)" "$lockfile_regenerated" \
  "$([ "$quick" -eq 1 ] && echo true || echo false)" "$steps" "$total" "$surgery" >>"$record"

echo "Recorded in $record: ${total}s, needed surgery: $surgery"
if [ -n "$bridge_touched" ]; then
  echo "Upstream changed files the fork edits:"
  printf '%s\n' "$bridge_touched" | sed 's/^/   /'
fi
case $previous in
  *'"neededSurgery":true'*)
    if [ "$surgery" = true ]; then
      echo "Two rehearsals in a row needed surgery. Review the seam before merging (#11)."
    fi
    ;;
esac

[ "$failed" -eq 0 ]
